### PR TITLE
User settings

### PR DESCRIPTION
**Pull request by pivnicek**

### CODE REVIEW

**Comment by Halama** [comment]
@pivnicek it would be nice to add also settings page to examples to be able to devel it on kbc-boostrap locally

**Comment by pivnicek** [comment]
@Halama good idea, thanks

**Comment by pivnicek** [comment]
@Halama ok, examples are ready.

**Comment by Halama** [comment]
@pivnicek Just one minor issue. The stripes should be without padding on sides:

image


This is what i see:
image

**Pull request merged**
